apiVersion: policy.jspolicy.com/v1beta1
kind: JsPolicy
metadata:
  name: "audit.resource.example"
spec:
  # This tells jspolicy to log every denied or errored request
  # to a CRD called JsPolicyViolations with the same name as the JsPolicy.
  # 
  # This is by default enabled. You can also specify Skip here to not
  # log such requests.
  auditPolicy: Log
  # Specify the max number of logged requests. Defaults to 20
  auditLogSize: 30
  operations: ["CREATE"]
  resources: ["pods"]
  javascript: |
    if (request.namespace === "default") {
      // Check the audit logs via `kubectl get jspolicyviolations audit.resource.example -o yaml`
      deny("Do not create pods in the default namespace");
    }
